function name=projectFolderName(name)
%PROJECTFOLDERNAME Validate a single portable directory name, never a path.
name=strtrim(string(name));
assert(isscalar(name)&&strlength(name)>0&&strlength(name)<=120&& ...
 isempty(regexp(char(name),'[<>:"/\\|?*\x00-\x1F]','once'))&& ...
 ~any(name==[".",".."])&&~endsWith(name,".")&& ...
 isempty(regexpi(char(name),'^(con|prn|aux|nul|com[1-9]|lpt[1-9])(\.|$)','once')), ...
 'inkprof:ProjectName','Use a project name of 1-120 characters without path separators or reserved filename characters.');
end
