% Copyright (c) 2026 Christer Törnkvist.
% SPDX-License-Identifier: GPL-3.0-or-later
% InkProf is free software under GNU GPL version 3 or later.
% Distributed WITHOUT ANY WARRANTY; see LICENSE and THIRD_PARTY_NOTICES.md.
function legal=reportLegalText(language)
arguments
 language (1,1) string = "sv"
end
% Shared existing report wording; shown only in the appendix after signatures.
legal.reproductionLiability="Utföraren av profileringen ansvarar inte för avvikelser som enbart beror på inneboende, fysiska begränsningar hos den aktuella kombinationen skrivare, papper och bläck, förutsatt att uppdraget i övrigt har utförts fackmässigt och enligt avtal. En ICC-profil innebär inte någon utfästelse om återgivning av färger, svärta, kontrast eller tonomfång utöver denna kombinations faktiska förmåga. Denna ansvarsbegränsning omfattar inte fel i utförarens eget arbete, bristfälliga instruktioner eller rekommendationer, avvikelser från uttryckligen avtalade åtaganden eller ansvar som följer av tvingande lag.";
legal.clientPrintResponsibility="Om beställaren (uppdragsgivaren) har skrivit ut målbilderna ansvarar beställaren för att utskrifterna har utförts enligt lämnade instruktioner och för att samtliga lämnade uppgifter är korrekta och fullständiga. Detta omfattar bland annat skrivare, papper, bläck, drivrutins- och färghanteringsinställningar, skalning, torktid samt hantering av utskrifterna. Utföraren av profileringen ansvarar inte för beställarens utskriftsarbete eller för fel i profil eller resultat i den mån dessa orsakas av brister i beställarens utskrifter eller av felaktiga eller ofullständiga uppgifter från beställaren. Mätcertifikatet redovisar resultatet för det mottagna underlaget; det innebär inte att utföraren har verifierat beställarens utskriftsprocess eller uppgifter. Denna ansvarsfördelning begränsar inte utförarens ansvar för egna fel, bristfälliga instruktioner eller skyldigheter enligt tvingande lag.";
legal.licensingNotice="InkProfs egen kod och dokumentation licensieras enligt GNU GPL version 3 eller senare. Externa program, typsnitt och annat tredjepartsmaterial omfattas av sina respektive villkor. GPL och ansvarsfriskrivningen ersätter inte tillstånd som kan krävas för annans upphovsrätt, varumärken eller patent. Mätcertifikatet är inte ett intyg om juridisk klarering av programmet eller dess användning. Fullständiga licenser och tredjepartsnotiser finns i LICENSE och THIRD_PARTY_NOTICES.md på https://github.com/chto0703009/InkProf-public.";
legal.warrantyNotice=inkprof.internal.warrantyNotice();
if language=="en"
 legal.reproductionLiability="The profiling provider is not responsible for deviations caused solely by inherent physical limitations of the printer, paper and ink combination, provided the service was otherwise performed professionally and in accordance with the agreement. An ICC profile does not promise colours, black level, contrast or tonal range beyond that combination's actual capabilities. This limitation does not cover errors in the provider's own work, inadequate instructions or recommendations, breaches of expressly agreed obligations, or liability under mandatory law.";
 legal.clientPrintResponsibility="If the client printed the targets, the client is responsible for following the supplied instructions and providing correct and complete information, including printer, paper, ink, driver and colour-management settings, scaling, drying time and print handling. The profiling provider is not responsible for the client's printing work or resulting profile errors to the extent caused by deficient prints or incorrect or incomplete client information. The certificate records results for the supplied evidence; it does not confirm that the provider verified the client's print process or information. This allocation does not limit responsibility for the provider's own errors, inadequate instructions or obligations under mandatory law.";
 legal.licensingNotice="InkProf code and documentation are licensed under GNU GPL version 3 or later. External software, fonts and other third-party materials have their own terms. GPL and the warranty disclaimer do not replace permissions required for third-party copyright, trademarks or patents. This certificate is not evidence of legal clearance of the software or its use. Full licences and notices are in LICENSE and THIRD_PARTY_NOTICES.md at https://github.com/chto0703009/InkProf-public.";
 legal.warrantyNotice=inkprof.internal.warrantyNotice("en");
end

end
