% Copyright (c) 2026 Christer Törnkvist.
% SPDX-License-Identifier: GPL-3.0-or-later
% InkProf is free software under GNU GPL version 3 or later.
% Distributed WITHOUT ANY WARRANTY; see LICENSE and THIRD_PARTY_NOTICES.md.
function methods=targetMethods()
%TARGETMETHODS Patch placement methods for RGB target design.
% id: stored in design JSON ("argyll" is OFPS, kept for older designs).
% flag: targen full-spread flag ("" = default OFPS).
% perceptual: placement uses perceptual distance, which needs a
% pre-conditioning profile to be meaningful (Argyll targen manual, -c).
methods=struct('id',{"mesh","argyll","argyll-incremental","argyll-quasi","argyll-perceptual-quasi", ...
    "argyll-bcc","argyll-perceptual-bcc","argyll-random","argyll-perceptual-random"}, ...
 'label',{"InkProf mesh refinement","Argyll OFPS (default, adaptive)","Argyll incremental far point", ...
    "Argyll quasi-random, device space","Argyll quasi-random, perceptual space", ...
    "Argyll body-centred cubic, device space","Argyll body-centred cubic, perceptual space", ...
    "Argyll random, device space","Argyll random, perceptual space"}, ...
 'flag',{"","","-t","-q","-Q","-i","-I","-r","-R"}, ...
 'perceptual',{false,true,false,false,true,false,true,false,true}, ...
 'short',{"InkProf mesh","Argyll OFPS","Argyll IFP","Argyll quasi-random (device)","Argyll quasi-random (perceptual)", ...
    "Argyll BCC (device)","Argyll BCC (perceptual)","Argyll random (device)","Argyll random (perceptual)"});
end
