% Distributed WITHOUT ANY WARRANTY; see LICENSE and THIRD_PARTY_NOTICES.md.
% Copyright (c) 2026 Christer Törnkvist.
% SPDX-License-Identifier: GPL-3.0-or-later
function text=tiffICCInstructions(info,iccFile)
% Separate pixel conversion from embedding an identifying ICC tag.
conversion="None by InkProf; source device RGB values are rendered directly.";
if isfield(info,'verification')
 v=info.verification;
 if v.profileApplied
  conversion="Applied once - absolute colorimetric, no BPC.";
 else
  conversion="None - device RGB reference set; ICC used for prediction only.";
 end
end
embedded="None (untagged TIFF).";
if iccFile~=""
 [~,name,ext]=fileparts(iccFile);
 embedded=string(name)+string(ext)+" (printer ICC; identifying tag only).";
 if isfield(info,'verification'),embedded=embedded+" Profile name: "+string(info.verification.profileName)+".";end
 embedded=embedded+newline+"Embedded ICC SHA-256: "+inkprof.internal.sha256(iccFile);
end
text=join(["PRINT THIS TARGET WITHOUT FURTHER COLOUR CONVERSION"; ...
 "Pixel encoding: printer device RGB (not sRGB or Adobe RGB)."; ...
 "ICC conversion: "+conversion;"Embedded ICC: "+embedded; ...
 "OPENING IN PHOTOSHOP"; ...
 "If Photoshop asks about the embedded profile, choose Discard the embedded profile / Don't color manage this document. Ignore the profile WITHOUT converting the RGB values."; ...
 "If the file opens with the embedded profile retained, use Edit > Assign Profile > Don't Color Manage This Document. This removes the document profile association without converting pixel values."; ...
 "Do NOT use Convert to Profile. Do NOT convert to Adobe RGB (1998) or sRGB. Do NOT assign a working-space profile."; ...
 "PRINTING"; ...
 "Print at 100% / actual size. Disable colour conversion in the application and any OS print path; in the Epson driver use Off (No Color Adjustment)."; ...
 "Do NOT select Photoshop Manages Colors with a printer ICC: this target already contains the device RGB values to be sent to the printer."; ...
 "Discarding a profile when opening is not enough: the print path and driver must also preserve the RGB numbers. If the application cannot print without conversion, use a print utility that preserves device RGB."; ...
 "Use the printer, paper, ink, media type and quality settings recorded for this target. Do not change them to compensate for an old profile."; ...
 "WHY A PRINTER ICC MAY BE EMBEDDED"; ...
 "It identifies the profile used by InkProf. Embedding does not change pixel values. This tag is not an instruction to apply the profile again."; ...
 "These instructions apply to this InkProf device-RGB print target. A printer profile embedded in an arbitrary image does not establish that it is print-ready."; ...
 "Imported source history may be unknown. ICC conversion and embedding are recorded separately above."],newline)+newline;
end
