function steps=workflowSteps()
% Stable IDs form the persisted workflow contract. Branches are explicit.
data={ ...
 'definition','1. Create / import RGB target',{}; ...
 'render','2. Save TIFF16',{'definition'}; ...
 'measurement','3. Measure / select measurement revision',{'render'}; ...
 'review','4. Review and accept measurement',{'measurement'}; ...
 'input','B1. Lock profiling inputs',{'review'}; ...
 'recipe','B2. Create recipe (manual workflow)',{'input'}; ...
 'profile','B3. Build ICC / automatic iteration',{'input'}; ...
 'checks','C1. Fit, Grid and C1',{'profile'}; ...
 'c2','C2. Save verification target as TIFF16',{'checks'}; ...
 'c2measurement','C2. Measure / select verification revision',{'c2'}; ...
 'c3','C3. Compare model and print',{'c2measurement'}; ...
 'feedback','6. Review feedback',{'c3'}; ...
 'approve','7. Approve for intended use',{'feedback'}; ...
 'export','8. Save ICC and measurement certificate',{'approve'}; ...
 'refine','Alternative: save refinement TIFF16',{'feedback'}; ...
 'refinemeasurement','Measure refinement',{'refine'}; ...
 'continue','Build next iteration',{'refinemeasurement'}};
steps=struct('id',data(:,1),'label',data(:,2),'requires',data(:,3));
end
