function steps=workflowSteps()
% Stable IDs form the persisted workflow contract. Branches are explicit.
data={ ...
 'definition','1. Skapa / importera RGB-mål',{}; ...
 'render','2. Spara TIFF16',{'definition'}; ...
 'measurement','3. Mät / välj mätrevision',{'render'}; ...
 'review','4. Granska och acceptera mätning',{'measurement'}; ...
 'input','B1. Lås profileringsunderlag',{'review'}; ...
 'recipe','B2. Skapa recept (manuell väg)',{'input'}; ...
 'profile','B3. Bygg ICC / automatisk iteration',{'input'}; ...
 'checks','C1. Fit, Grid och C1',{'profile'}; ...
 'c2','C2. Spara kontrollmål som TIFF16',{'checks'}; ...
 'c2measurement','C2. Mät / välj kontrollrevision',{'c2'}; ...
 'c3','C3. Jämför modell och utskrift',{'c2measurement'}; ...
 'feedback','6. Granska återkoppling',{'c3'}; ...
 'approve','7. Godkänn för avsedd användning',{'feedback'}; ...
 'export','8. Spara ICC och slutrapport',{'approve'}; ...
 'refine','Alternativ: spara komplettering TIFF16',{'feedback'}; ...
 'refinemeasurement','Mät komplettering',{'refine'}; ...
 'continue','Bygg nästa iteration',{'refinemeasurement'}};
steps=struct('id',data(:,1),'label',data(:,2),'requires',data(:,3));
end
