% Copyright (c) 2026 Christer Törnkvist.
% SPDX-License-Identifier: GPL-3.0-or-later
% InkProf is free software under GNU GPL version 3 or later.
% Distributed WITHOUT ANY WARRANTY; see LICENSE and THIRD_PARTY_NOTICES.md.
function steps=workflowSteps(mode)
if nargin<1,mode="profiling";end
% Stable IDs form the persisted workflow contract. Branches are explicit.
data={ ...
 'definition','1. Create / import RGB target',{}; ...
 'render','2. Save TIFF16',{'definition'}; ...
 'measurement','3. Measure / select measurement revision',{'render'}; ...
 'review','4. Review and accept measurement',{'measurement'}; ...
 'input','B1. Lock profiling inputs',{'review'}; ...
 'recipe','B2. Create recipe (manual workflow)',{'input'}; ...
 'profile','B3. Build ICC / automatic iteration',{'input'}; ...
 'checks','C1. Fit, Grid and C1',{'profile'}; ...
 'c2','C2. Save verification target as TIFF16',{'checks'}; ...
 'c2measurement','C2. Measure / select verification revision',{'c2'}; ...
 'c3','C3. Compare model and print',{'c2measurement'}; ...
 'feedback','6. Review feedback',{'c3'}; ...
 'approve','7. Approve for intended use',{'feedback'}; ...
 'export','8. Save ICC and measurement certificate',{'approve'}; ...
 'refine','Alternative: save refinement TIFF16 (errors, image or gamut)',{'checks'}; ...
 'refinemeasurement','Measure refinement',{'refine'}; ...
 'continue','Build next iteration',{'refinemeasurement'}; ...
 'compare','Compare with previous iteration',{'profile'}; ...
 'numericalExport','Save ICC + measurement certificate without print verification',{'checks'}};
steps=struct('id',data(:,1),'label',data(:,2),'requires',data(:,3),'enabled',true);
if mode=="verification"
 active=["profile","c2","c2measurement","c3","feedback","approve","export"];
 labels=["1. Import existing RGB printer ICC","2. Save verification TIFF16 (575 suggested)", ...
  "3. Measure / select verification revision","4. Analyse profile and print", ...
  "5. Review feedback","6. Record assessment for intended use","7. Save measurement certificate"];
 for k=1:numel(steps)
  at=find(active==string(steps(k).id));steps(k).enabled=~isempty(at);
  if ~isempty(at),steps(k).label=char(labels(at));end
  if string(steps(k).id)=="profile",steps(k).requires={};end
  if string(steps(k).id)=="c2",steps(k).requires={'profile'};end
 end
end
end
