function paths=writeWorkflowFinalReport(w,profile,folder,options)
arguments
 w
 profile (1,1) string
 folder (1,1) string
 options.User (1,1) string = string(java.lang.System.getProperty('user.name'))
end
% Save a portable human report and structured evidence after the ICC is saved.
assert(isfile(profile),'inkprof:FinalReport','Spara ICC-profilen innan mätcertifikatet skapas.');
assert(strlength(strtrim(options.User))>0&&strlength(options.User)<=120,'inkprof:FinalReport','Ange rapportens användare (1-120 tecken).');
project=jsondecode(fileread(fullfile(w.Root,'inkprof-project.json')));
source=w.output('profile','profile');digest=inkprof.internal.sha256(profile);
assert(digest==inkprof.internal.sha256(source),'inkprof:Integrity','Sparad ICC skiljer sig från vald kandidat.');
approval=jsondecode(fileread(w.output('approve','approval')));
assert(string(approval.profileSHA256)==digest&&string(approval.reportSHA256)==inkprof.internal.sha256(w.output('c3','report')), ...
 'inkprof:FinalReport','Godkännandet gäller en annan ICC eller C3-rapport.');
r=struct('schemaVersion',1,'documentType',"inkprof.final-report",'status',"icc-saved", ...
 'createdUTC',string(datetime('now','TimeZone','UTC','Format',"yyyy-MM-dd'T'HH:mm:ss'Z'")), ...
 'pageHeader',"InkProf Quality Profiling RGB printer",'reportDate',string(datetime('now','Format','yyyy-MM-dd')),'reportUser',options.User, ...
 'project',struct('id',project.projectId,'name',project.name),'iteration',w.State.cycle, ...
 'iterationId',w.State.iterationId,'parentIterationId',w.State.parentIterationId, ...
 'profile',struct('file',"profile.icc",'projectPath',w.relative(profile),'sha256',digest,'byteIdentical',true), ...
 'printing',struct('performedOutsideApp',true,'verifiedByApp',false,'reportedSettings',project.printing), ...
 'approval',approval,'sources',struct,'results',struct,'history',{w.State.history});
r.documentTitle="InkProf - mätcertifikat";
r.certificateId=string(java.util.UUID.randomUUID());
r.certificateScope="Mätcertifikatet redovisar sparade mätresultat och användarens bedömning för angiven ICC-profil och projektkonfiguration. Det är inte en ackrediterad certifiering eller ett intyg om ISO-överensstämmelse.";
r.reproductionLimits="Resultatet med en ICC-profil är beroende av vad kombinationen skrivare, papper och bläck fysiskt kan återge. Papperets vithet, yta och optiska vitmedel, bläckets egenskaper samt skrivarens och drivrutinens inställningar begränsar färgomfång, svärta, kontrast och tonåtergivning. En ICC-profil beskriver denna kombination och hjälper färghanteringen att återge färger inom dess förmåga; den kan inte skapa färger eller kontrast som material och utrustning inte kan återge. Det finns därför en fysisk gräns för hur nära en önskad referens utskriften kan komma. Färger utanför färgomfånget behöver anpassas. Fler mätpunkter eller ytterligare profiliterationer garanterar inte ett bättre resultat. Uppmätta avvikelser påverkas även av utskriftsstabilitet, torktid, mätvillkor och betraktningsljus. Resultatet gäller de dokumenterade villkoren; ändringar kan kräva ny profilering och verifiering.";
r.reproductionLiability="Utföraren av profileringen ansvarar inte för avvikelser som enbart beror på inneboende, fysiska begränsningar hos den aktuella kombinationen skrivare, papper och bläck, förutsatt att uppdraget i övrigt har utförts fackmässigt och enligt avtal. En ICC-profil innebär inte någon utfästelse om återgivning av färger, svärta, kontrast eller tonomfång utöver denna kombinations faktiska förmåga. Denna ansvarsbegränsning omfattar inte fel i utförarens eget arbete, bristfälliga instruktioner eller rekommendationer, avvikelser från uttryckligen avtalade åtaganden eller ansvar som följer av tvingande lag.";
r.clientPrintResponsibility="Om beställaren (uppdragsgivaren) har skrivit ut målbilderna ansvarar beställaren för att utskrifterna har utförts enligt lämnade instruktioner och för att samtliga lämnade uppgifter är korrekta och fullständiga. Detta omfattar bland annat skrivare, papper, bläck, drivrutins- och färghanteringsinställningar, skalning, torktid samt hantering av utskrifterna. Utföraren av profileringen ansvarar inte för beställarens utskriftsarbete eller för fel i profil eller resultat i den mån dessa orsakas av brister i beställarens utskrifter eller av felaktiga eller ofullständiga uppgifter från beställaren. Mätcertifikatet redovisar resultatet för det mottagna underlaget; det innebär inte att utföraren har verifierat beställarens utskriftsprocess eller uppgifter. Denna ansvarsfördelning begränsar inte utförarens ansvar för egna fel, bristfälliga instruktioner eller skyldigheter enligt tvingande lag.";
r.signature=struct('status',"unsigned",'method',"handwritten on printed PDF", ...
 'statement',"Med min underskrift bekräftar jag att jag har granskat mätcertifikatet och dess angivna förutsättningar, resultat, begränsningar och ansvarsfördelning.");
r.projectDetails=struct('label',{},'value',{});
addDetail("Projekt",project.name);addDetail("Projekt-ID",project.projectId);
addDetail("Dokumentdatum",r.reportDate);addDetail("Dokument upprättat av",r.reportUser);
if isfield(project,'user'),addDetail("Projektansvarig",project.user);end
if isfield(project,'createdUTC'),addDetail("Projekt skapat (UTC)",project.createdUTC);end
labels={"printer","Skrivare";"paper","Papper";"paperSurface","Pappersyta";"ink","Bläck / bläckuppsättning"; ...
 "media","Drivrutinens mediaval";"driver","Drivrutin / RIP";"quality","Utskriftskvalitet"; ...
 "printPath","Utskriftsprogram";"colorManagement","Färghantering vid utskrift";"dryingHours","Torktid (timmar)";"settings","Övriga skrivarinställningar"};
for k=1:size(labels,1)
 value="Ej angivet";if isfield(project.printing,labels{k,1}),value=project.printing.(labels{k,1});end
 addDetail(labels{k,2},value);
end
r.warrantyNotice=inkprof.internal.warrantyNotice();
% Copy the referenced reports alongside the ICC; links survive moving exports.
pairs={'checks','fit';'checks','grid';'checks','c1';'c3','report';'feedback','feedback'; ...
 'approve','approval';'measurement','measurement';'c2measurement','measurement';'profile','job'};
for k=1:size(pairs,1)
 step=pairs{k,1};key=pairs{k,2};original=w.output(step,key);
 name=string(step)+"-"+key+".json";copyfile(original,fullfile(folder,name));
 id=matlab.lang.makeValidName(step+"_"+key);
 r.sources.(id)=struct('file',name,'projectPath',w.relative(original),'sha256',inkprof.internal.sha256(original));
 data=jsondecode(fileread(original));
 keep=["summary","groups","grayBalance","repeatedPrintedPatches","pairedScanQuality","roundtripDeltaE00", ...
  "grossFailureAlerts","allNegativeControlsDetected","recommendation","priorities","status","measurementCondition","measuredSourcePatches","colorimetry","limitations"];
 reduced=struct;
 for field=keep,if isfield(data,field),reduced.(field)=data.(field);end,end
 r.results.(id)=reduced;
end
if isfield(w.State.steps.profile.outputs,'iteration')
 src=w.output('profile','iteration');copyfile(src,fullfile(folder,'iteration.json'));
 r.sources.iteration=struct('file',"iteration.json",'projectPath',w.relative(src),'sha256',inkprof.internal.sha256(src));
 iteration=jsondecode(fileread(src));
 for key=["selection","roles","parameters"]
  if isfield(iteration,key),r.results.iteration.(key)=iteration.(key);end
 end
end
paths=struct('pdf',fullfile(folder,'final-report.pdf'),'html',fullfile(folder,'final-report.html'),'json',fullfile(folder,'final-report.json'),'text',fullfile(folder,'final-report.txt'));
if isfield(w.State.steps.c2.outputs,'reference')
 reference=w.output('c2','reference');
 ref=jsondecode(fileread(reference));
 assert(string(ref.printerProfile.sha256)==digest,'inkprof:FinalReport','3D-underlaget hör till en annan ICC.');
 f=inkprof.showVerificationLab(reference,Visible=false);
 cleanFigure=onCleanup(@()delete(f));
 exportgraphics(f,fullfile(folder,'profile-lab-3d.png'),'Resolution',160);
 animationData=struct('lab',f.UserData.lab,'rgb',f.UserData.previewRGB);clear cleanFigure
 copyfile(reference,fullfile(folder,'verification.json'));
 r.visualization=struct('file',"profile-lab-3d.png",'kind',"Predicted C2 patch Lab D50; not measured or full gamut", ...
  'reference',"verification.json",'referenceSHA256',inkprof.internal.sha256(reference));
end
r.patchOutliers=inkprof.internal.certificatePatchOutliers(jsondecode(fileread(w.output('c3','report'))));
r.fwa=inkprof.internal.fwaReportSummary(r.results.checks_fit,r.results.c3_report,project.printing,digest);
inkprof.internal.writeJson(paths.json,r);
lines=["INKPROF – MÄTCERTIFIKAT";"Projekt: "+string(project.name);"Projekt-ID: "+string(project.projectId);"Datum: "+r.reportDate;"Användare: "+r.reportUser; ...
 "Iteration: "+w.State.cycle;"Iterations-ID: "+w.State.iterationId;"Tid UTC: "+r.createdUTC; ...
 "Certifikat-ID: "+r.certificateId;"";r.certificateScope;"";"PROJEKT OCH UTSKRIFTSVILLKOR"; ...
 string({r.projectDetails.label})'+": "+string({r.projectDetails.value})'; ...
 "";"FWA/OBA - VAL OCH RESULTAT";r.fwa.summaryText; ...
 "";"FYSISK ÅTERGIVNINGSFÖRMÅGA OCH RESULTATETS GRÄNSER";r.reproductionLimits; ...
 "";"ANSVAR FÖR UTRUSTNINGENS OCH MATERIALENS BEGRÄNSNINGAR";r.reproductionLiability; ...
 "";"BESTÄLLARENS UTSKRIFTER OCH UPPGIFTER";r.clientPrintResponsibility; ...
 "";"GARANTI OCH ANSVAR";r.warrantyNotice;"";"SPARAD ICC";"Fil: profile.icc";"SHA-256: "+digest;"Byte-identisk med vald kandidat."; ...
 "";"SLUTLIG BEDÖMNING";string(approval.notes);""; ...
 "MÄTRESULTAT – FÄRGPROV OCH ΔE00";r.patchOutliers.basis;r.patchOutliers.message;r.patchOutliers.colourNote];
fit=r.results.checks_fit;
for patch=reshape(r.patchOutliers.patches,1,[])
 lines(end+1)=sprintf('Sida %d / %s | ID %s | %s | sRGB %s | ΔE00 %.4f | över gräns %.4f',patch.page,patch.coordinate,patch.sampleId,patch.role,patch.hex,patch.deltaE00,patch.excess);
end
profileColorimetry=struct;if isfield(fit,'colorimetry'),profileColorimetry=fit.colorimetry;end
lines=[lines;"";"UTSKRIFT OCH MÄTNING"; ...
 "Appen sparar TIFF16. Användaren skriver ut separat; appen genomför instrumentmätningen."; ...
 "Utskriftskedjan har inte verifierats av appen. Ej dokumenterade villkor förblir okända."; ...
 "Projektets rapporterade utskriftsvillkor: "+string(jsonencode(project.printing)); ...
 "FWA/OBA och beräkningsvillkor för profilen: "+string(jsonencode(profileColorimetry)); ...
 "Profileringsmätning: "+string(jsonencode(r.results.measurement_measurement)); ...
 "Kontrollmätning: "+string(jsonencode(r.results.c2measurement_measurement)); ...
 "";"NUMERISKA KONTROLLER OCH ÅTERKOPPLING"; ...
 "Grid: "+string(jsonencode(r.results.checks_grid));"C1: "+string(jsonencode(r.results.checks_c1)); ...
 "Återkoppling: "+string(jsonencode(r.results.feedback_feedback)); ...
 "";"ITERATIONSHISTORIK (UTC)"];
h=w.State.history;if isstruct(h),h=num2cell(h);end
for k=1:numel(h)
 e=h{k};lines(end+1)=string(e.utc)+" | iteration "+e.cycle+" | "+string(e.step)+" | "+string(e.status);
end
lines=[lines;r.createdUTC+" | iteration "+w.State.cycle+" | ICC sparad och mätcertifikat skapad"; ...
 "";"UNDERLAG OCH SPÅRBARHET"];
for key=string(fieldnames(r.sources))'
 a=r.sources.(key);lines=[lines;string(a.file);"  Projekt: "+a.projectPath;"  SHA-256: "+a.sha256]; %#ok<AGROW>
end
lines=[lines;"";"Resultaten beskriver det sparade underlaget. Användarens godkännande är inte ISO-certifiering."; ...
 "Kompletta rådata och äldre kandidater bevaras i projektet. Rapportens JSON innehåller strukturerade resultat och historik."];
lines=[lines;"";"UNDERSKRIFT";r.signature.statement;"Certifikat-ID: "+r.certificateId; ...
 "Ort och datum: __________________________________________"; ...
 "Underskrift: _____________________________________________"; ...
 "Namnförtydligande: _______________________________________"; ...
 "Organisation / roll: ______________________________________"];
writeText(paths.text,strjoin(lines,newline));
projectHTML="<h2>Projekt och utskriftsvillkor</h2>";
for detail=r.projectDetails
 projectHTML=projectHTML+"<p><strong>"+esc(detail.label)+":</strong> "+esc(detail.value)+"</p>";
end
html="<!doctype html><html lang='sv'><meta charset='utf-8'><meta name='viewport' content='width=device-width'><title>InkProf – mätcertifikat</title>"+ ...
 "<style>body{font:16px/1.5 system-ui,sans-serif;color:#19303c;max-width:1050px;margin:40px auto;padding:0 24px}h1{font-size:32px}h2{margin-top:32px}table{border-collapse:collapse;width:100%}th,td{border-bottom:1px solid #ccd8de;padding:9px;text-align:left}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#f3f6f7;padding:20px}a{color:#146078}code{overflow-wrap:anywhere}@media print{body{margin:0;font-size:11px}tr{break-inside:avoid}}</style>"+ ...
 "<h1>InkProf – mätcertifikat</h1><p>"+esc(string(project.name))+" · Iteration "+w.State.cycle+" · "+esc(r.createdUTC)+"</p>"+ ...
 "<p>Certifikat-ID: "+esc(r.certificateId)+"</p><p>"+esc(r.certificateScope)+"</p>"+projectHTML+ ...
 "<h2>Sparad ICC-profil</h2><p><a href='profile.icc'>profile.icc</a></p><p>SHA-256: <code>"+digest+"</code></p>"+ ...
 "<h2>Slutlig bedömning</h2><p>"+esc(string(approval.notes))+"</p><h2>Mätresultat – färgprov och ΔE00</h2>"+ ...
 "<p>"+esc(r.patchOutliers.basis)+"</p><p>"+esc(r.patchOutliers.message)+"</p><p>"+esc(r.patchOutliers.colourNote)+"</p>";
for k=1:3:r.patchOutliers.count
 html=html+"<div class='patch-row' style='display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin-bottom:8px;font-size:9pt'>";
 for j=k:min(k+2,r.patchOutliers.count)
  patch=r.patchOutliers.patches(j);mark="";if patch.clipped,mark="*";end
  html=html+"<div style='border:1px solid #ccd8de;padding:6px;overflow-wrap:anywhere'><span style='display:inline-block;width:100%;height:40px;border:1px solid #777;background:"+patch.hex+";print-color-adjust:exact;-webkit-print-color-adjust:exact'></span> "+esc(patch.hex+mark)+ ...
   "<br><strong>"+esc("ID "+patch.sampleId)+"</strong> · "+esc("sida "+patch.page+" / "+patch.coordinate)+ ...
   "<br>"+esc(patch.role)+" · ΔE00 <strong>"+compose('%.4f',patch.deltaE00)+"</strong></div>";
 end
 html=html+"</div>";
end
html=html+"<p>Källa: <a href='"+esc(r.patchOutliers.source)+"'>MediaStandard Print 2018, tabell 30</a>.</p><p>Träningsfel är inte oberoende verifiering. Utskrift sker separat; appen intygar inte utskriftskedjan.</p>"+ ...
 "<h2>FWA/OBA - val och resultat</h2><p>"+replace(esc(r.fwa.summaryText),newline,"<br>")+"</p>"+ ...
 "<h2>Fysisk återgivningsförmåga och resultatets gränser</h2><p>"+esc(r.reproductionLimits)+"</p>"+ ...
 "<h2>Ansvar för utrustningens och materialens begränsningar</h2><p>"+esc(r.reproductionLiability)+"</p>"+ ...
 "<h2>Beställarens utskrifter och uppgifter</h2><p>"+esc(r.clientPrintResponsibility)+"</p>"+ ...
 "<h2>Garanti och ansvar</h2><p>"+esc(r.warrantyNotice)+"</p>"+ ...
 "<h2>Underlag</h2><ul><li><a href='final-report.json'>Strukturerat mätcertifikat (JSON)</a></li><li><a href='final-report.txt'>Mätcertifikat som text</a></li>";
for key=string(fieldnames(r.sources))'
 name=r.sources.(key).file;html=html+"<li><a href='"+esc(name)+"'>"+esc(name)+"</a></li>";
end
html=html+"<li><a href='final-report.pdf'>Mätcertifikat som PDF</a></li></ul>";
if isfield(r,'visualization')
 plotData=replace(string(jsonencode(animationData)),"<",string(char(92))+"u003c");
 html=html+"<section class='lab-view'><h2>Profilens beräknade kontrollfärger i 3D</h2><p>Automatiskt roterande kontrollpatchar i Lab D50; inte mätningar eller hela skrivarens färgomfång.</p>"+ ...
 "<script type='application/json' class='lab-data'>"+plotData+"</script><canvas class='lab-canvas' role='img' aria-label='Automatically rotating predicted control colours in CIELAB D50'></canvas><img class='lab-still'  src='profile-lab-3d.png' alt='Profilens beräknade kontrollpatchar i Lab 3D' style='width:100%;height:auto'></section>";
end
signatureStart=find(lines=="UNDERSKRIFT",1,'last');
% The visual results already appear above; keep their text equivalent in TXT only.
resultStart=find(lines=="MÄTRESULTAT – FÄRGPROV OCH ΔE00",1);
resultEnd=find(lines=="UTSKRIFT OCH MÄTNING",1);
appendixLines=[lines(1:resultStart-1);lines(resultEnd:signatureStart-1)];
html=html+"<h2>Fullständig redovisning och historik</h2><pre>"+esc(strjoin(appendixLines,newline))+"</pre>"+ ...
 "<section class='certificate-signature' style='height:225mm;display:flex;flex-direction:column;break-inside:avoid'><h2>Underskrift av mätcertifikat</h2>"+ ...
 "<p>Projekt: "+esc(string(project.name))+"</p><p>Certifikat-ID: "+esc(r.certificateId)+"</p><p>Dokumentdatum: "+esc(r.reportDate)+"</p>"+ ...
 "<p>ICC SHA-256: "+digest+"</p><div style='margin-top:auto'><p>"+esc(r.signature.statement)+"</p>"+ ...
 "<p style='margin-top:15mm'>Ort och datum: __________________________________________</p>"+ ...
 "<p style='margin-top:15mm'>Underskrift: _____________________________________________</p>"+ ...
 "<p style='margin-top:15mm'>Namnförtydligande: _______________________________________</p>"+ ...
 "<p style='margin-top:15mm'>Organisation / roll: ______________________________________</p></div></section></html>";
config=inkprof.paths();
furniture=struct('header',r.pageHeader,'date',r.reportDate,'user',r.reportUser);
pages=string(fileread(fullfile(config.Root,'resources','workflow-report-pages.html')));
metadata=string(jsonencode(furniture));metadata=replace(metadata,"<",string(char(92))+"u003c");
pages=replace(pages,"__REPORT_FURNITURE__",metadata);
animation=string(fileread(fullfile(config.Root,'resources','workflow-report-3d.html')));
html=replace(html,"</html>",pages+animation+"</html>");
writeText(paths.html,html);
inkprof.runPython(fullfile(config.Root,'analysis','workflow_final_pdf.py'),string(folder),RequiredModules="reportlab",WorkingDirectory=config.Root);
    function addDetail(label,value)
        value=strtrim(string(value));if isempty(value)||strlength(value)==0||value=="unknown",value="Ej angivet";end
        r.projectDetails(end+1)=struct('label',string(label),'value',value);
    end

end
function text=esc(text)
text=replace(string(text),["&","<",">",string(char(34)),"'"],["&amp;","&lt;","&gt;","&quot;","&#39;"]);
end
function writeText(file,text)
fid=fopen(file,'w','n','UTF-8');assert(fid>=0,'inkprof:IO','Kan inte spara mätcertifikatet.');
cleanup=onCleanup(@()fclose(fid));fprintf(fid,'%s\n',text);
end
