function file=selectMeasurementRevision(folder,target)
%SELECTMEASUREMENTREVISION Choose by saved time and patch count, not UUID.
file="";revisions=inkprof.internal.measurementRevisions(folder,target);
if isempty(revisions)
 uiwait(msgbox('No complete, intact measurement revision for this target was found. Finish and save the measurement, or import an existing measurement file.', ...
  'Measurement revisions','warn','modal'));return
end
[index,accepted]=listdlg('Name','Select measurement revision', ...
 'PromptString',{'Select a saved revision for this target. Latest saved is selected.'; ...
 'Times are local file-save times. Complete means all patches exist; review follows in the next step.'}, ...
 'ListString',cellstr(string({revisions.label})),'SelectionMode','single', ...
 'InitialValue',1,'ListSize',[850 300],'OKString','Use revision','CancelString','Cancel');
if accepted,file=revisions(index).file;end
end
