// Distributed WITHOUT ANY WARRANTY; see LICENSE and THIRD_PARTY_NOTICES.md.
// Copyright (c) 2026 Christer Törnkvist.
// SPDX-License-Identifier: GPL-3.0-or-later
// Shared self-contained surface and measured-point views.
(()=>{const seen=window.inkprofLabViewsSeen||(window.inkprofLabViewsSeen=new WeakSet());function init(root){if(!root||seen.has(root))return;seen.add(root);
const canvas=root.querySelector('canvas'),ctx=canvas.getContext('2d'),data=JSON.parse(root.querySelector('script').textContent),mode=root.querySelector('.lab-mode'),level=root.querySelector('.lab-level'),band=root.querySelector('.lab-band'),auto=root.querySelector('.lab-auto'),status=root.querySelector('.lab-status');
const surface=data.kind==='surface',vertices=data.vertices,extent=Math.max(20,...vertices.flatMap(p=>[Math.abs(p[1]),Math.abs(p[2])])),limit=Math.ceil(extent/20)*20,scale=190/limit;let yaw=.65,pitch=.2,drag=null,last=0;
root.querySelector('.lab-band-label').hidden=surface;
function segments(l){const out=[];for(const t of data.triangles){const hits=[];for(let k=0;k<3;k++){const a=vertices[t[k]],b=vertices[t[(k+1)%3]];if(Math.abs(a[0]-l)<1e-9&&Math.abs(b[0]-l)<1e-9){hits.push(a.slice(1),b.slice(1));}else if((a[0]-l)*(b[0]-l)<=0&&Math.abs(b[0]-a[0])>1e-9){const f=(l-a[0])/(b[0]-a[0]);hits.push([a[1]+f*(b[1]-a[1]),a[2]+f*(b[2]-a[2])]);}}
const u=hits.filter((h,i)=>!hits.slice(0,i).some(q=>Math.hypot(h[0]-q[0],h[1]-q[1])<1e-8));if(u.length===2)out.push([u[0],u[1],t]);else if(u.length>2)u.forEach((a,i)=>out.push([a,u[(i+1)%u.length],t]));}return out;}
function draw(){const W=canvas.width,H=canvas.height,two=mode.value==='2d',l=Number(level.value),half=Math.max(0,Math.min(50,Number(band.value)||0));ctx.clearRect(0,0,W,H);ctx.fillStyle='#f5f7f8';ctx.fillRect(0,0,W,H);level.disabled=!two;band.disabled=!two;auto.disabled=two;root.querySelector('output').textContent=l;
const project=([L,a,b])=>{if(two)return[W/2+a*scale,H/2-b*scale,0];const x=a*Math.cos(yaw)-b*Math.sin(yaw),z=a*Math.sin(yaw)+b*Math.cos(yaw),y=L-50;return[W/2+x*scale,H/2-3*(y*Math.cos(pitch)-z*Math.sin(pitch)),z*Math.cos(pitch)+y*Math.sin(pitch)];};
const colour=rgb=>'rgb('+rgb.map(x=>Math.round(255*x)).join(',')+')';let shown=0;
if(surface){if(two){for(const [a,b,t] of segments(l)){const p=project([l,...a]),q=project([l,...b]);ctx.strokeStyle=colour([0,1,2].map(c=>t.reduce((s,i)=>s+data.rgb[i][c],0)/3));ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(...p.slice(0,2));ctx.lineTo(...q.slice(0,2));ctx.stroke();shown++;}}
else{const p=vertices.map(project);for(const t of [...data.triangles].sort((a,b)=>b.reduce((s,i)=>s+p[i][2],0)-a.reduce((s,i)=>s+p[i][2],0))){ctx.beginPath();t.forEach((i,j)=>j?ctx.lineTo(...p[i].slice(0,2)):ctx.moveTo(...p[i].slice(0,2)));ctx.closePath();ctx.fillStyle=colour([0,1,2].map(c=>t.reduce((s,i)=>s+data.rgb[i][c],0)/3));ctx.fill();}}}
else vertices.map((p,i)=>({p,i,q:project(p)})).filter(v=>!two||Math.abs(v.p[0]-l)<=half).sort((a,b)=>b.q[2]-a.q[2]).forEach(v=>{ctx.fillStyle=colour(data.rgb[v.i]);ctx.beginPath();ctx.arc(v.q[0],v.q[1],4,0,2*Math.PI);ctx.fill();ctx.strokeStyle='#263b49';ctx.lineWidth=.6;ctx.stroke();shown++;});
function line(a,b,label){a=project(a);b=project(b);for(const [c,w] of [['white',4],['#263b49',1.2]]){ctx.strokeStyle=c;ctx.lineWidth=w;ctx.beginPath();ctx.moveTo(...a.slice(0,2));ctx.lineTo(...b.slice(0,2));ctx.stroke();}ctx.fillStyle='#263b49';ctx.font='16px sans-serif';ctx.fillText(label,b[0]+5,b[1]-(label.startsWith('L*')?22:6));}
line([two?l:0,-limit,0],[two?l:0,limit,0],'a*');line([two?l:0,0,-limit],[two?l:0,0,limit],'b*');
if(!two){line([0,0,0],[100,0,0],'L* (a*=b*=0)');for(let x=0;x<=100;x+=20){const p=project([x,0,0]);ctx.fillText(x,p[0]+7,p[1]+4);}}
else{ctx.font='12px sans-serif';for(let x=-limit;x<=limit;x+=20){const a=project([l,x,0]),b=project([l,0,x]);ctx.fillText(x,a[0]-8,H/2+18);if(x)ctx.fillText(x,W/2+5,b[1]+4);}}
ctx.fillStyle='#263b49';ctx.font='16px sans-serif';ctx.fillText(two?'L* = '+l+(surface?' exact surface slice':' ± '+half):'L* / a* / b* — drag to rotate',15,24);
status.textContent=data.label+' · '+(two?(surface?shown+' intersecting surface segments':shown+' of '+vertices.length+' measured points in the L* band'):'all L* levels')+'. '+(surface?'ICC prediction, not a measurement.':'Actual measured colours, not a gamut boundary.');}
[mode,level,band,auto].forEach(e=>e.oninput=draw);canvas.onpointerdown=e=>{if(mode.value==='2d')return;drag=[e.clientX,e.clientY];auto.checked=false;canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(drag){yaw+=(e.clientX-drag[0])*.01;pitch=Math.max(-1.3,Math.min(1.3,pitch+(e.clientY-drag[1])*.01));drag=[e.clientX,e.clientY];draw();}};canvas.onpointerup=canvas.onpointercancel=()=>drag=null;
function frame(t){if(!root.isConnected)return;if(mode.value==='3d'&&auto.checked&&t-last>65){yaw+=.012;draw();last=t;}requestAnimationFrame(frame);}draw();requestAnimationFrame(frame);}
init(document.currentScript.previousElementSibling);document.addEventListener('inkprof-report-ready',()=>document.querySelectorAll('.gamut-view').forEach(init));})();
