# Distributed WITHOUT ANY WARRANTY; see LICENSE and THIRD_PARTY_NOTICES.md.
# Copyright (c) 2026 Christer Törnkvist.
# SPDX-License-Identifier: GPL-3.0-or-later
"""Separate the ICC inverse, rendered pixels and measured-print evidence."""
import json
from pathlib import Path
import numpy as np
import colour
import tifffile
from profile_grid import sha
from icc_lookup import lookup, evidence as lookup_evidence


def summary(values):
    a=np.asarray(values,float)
    return dict(count=len(a),mean=float(a.mean()),median=float(np.median(a)),p95=float(np.percentile(a,95)),max=float(a.max()))


def inside(root,name):
    p=(root/name).resolve()
    if not p.is_relative_to(root.resolve()):raise ValueError('Chain artifact escapes target package')
    return p


def analyse(reference,root,profile,exe,measured):
    root=Path(root);patches=reference['patches']
    desired=np.array([p['referenceLabD50Absolute'] for p in patches],float)
    saved=np.array([p['deviceRGB16'] for p in patches],float)/65535
    b2a=lookup(exe,profile,desired,'b','a')
    inverse_lab=lookup(exe,profile,b2a,'f','a')
    saved_lab=lookup(exe,profile,saved,'f','a')
    unique=np.array([p['role'] not in ('repeat','paperwhite') for p in patches])
    inverse_de=colour.delta_E(desired,inverse_lab,method='CIE 2000')
    quantized_de=colour.delta_E(desired,saved_lab,method='CIE 2000')
    measured_byid={str(p['sampleId']):p for p in measured}
    rows=[dict(sampleId=str(p['id']),inverseRoundtripDE00=float(inverse_de[i]),
               savedRGBRoundtripDE00=float(quantized_de[i]),
               inverseVsSavedMaxChannel16Codes=float(np.max(abs(b2a[i]*65535-saved[i]*65535)))) for i,p in enumerate(patches)]
    result=dict(colourEngine=lookup_evidence(profile),inverse=dict(status='available',label='Desired Lab vs ICC inverse/forward round-trip',summary=summary(inverse_de[unique]),savedRGBSummary=summary(quantized_de[unique])),
                tiff=dict(status='unavailable',label='Saved device RGB vs actual TIFF pixels'),
                print=dict(status='unavailable',label='Measured print vs ICC prediction from actual TIFF RGB'),patches=rows,sources=[],
                limitations=['Numerical inverse agreement does not establish physical reachability.',
                'TIFF checks sample the central 3 x 3 pixels of each patch, not the entire patch.',
                'A print disagreement cannot alone distinguish model error, print settings, colour conversion or measurement error.',
                'Current ICC B2A is compared with saved C2 RGB; references generated by another inversion policy may legitimately differ.'])
    folder=inside(root,reference['printPackage']['folder']);layout=folder/'layout.json'
    if not layout.is_file():result['tiff']['reason']='Saved layout.json unavailable';return result
    placements=json.loads(layout.read_text())['patches'];placed={str(p['sampleId']):p for p in placements if not p.get('isPadding',False)}
    result['sources'].append(dict(path=str(layout),sha256=sha(layout)))
    images={};observed=[];mismatches=[]
    try:
        for i,p in enumerate(patches):
            key=str(p['placement'].get('sampleId',p['id']));q=placed[key]
            file=inside(folder,q['tiff'])
            if file not in images:
                digest=sha(file)
                with tifffile.TiffFile(file) as t:
                    page=t.pages[0];a=page.asarray()
                    if a.dtype!=np.uint16 or a.ndim!=3 or a.shape[2]!=3:raise ValueError('Expected RGB16 TIFF')
                    resolution=page.tags['ResolutionUnit'].value
                    if int(resolution)!=2:raise ValueError('TIFF resolution must be in inches')
                    xr=page.tags['XResolution'].value;yr=page.tags['YResolution'].value
                    images[file]=(a,xr[0]/xr[1],yr[0]/yr[1],digest)
                result['sources'].append(dict(path=str(file),sha256=digest))
            a,dx,dy,digest=images[file];x,y,w,h=q['rectMm'];cx=int(round((x+w/2)*dx/25.4));cy=int(round((y+h/2)*dy/25.4))
            if not (1<=cx<a.shape[1]-1 and 1<=cy<a.shape[0]-1):raise ValueError('Patch center outside TIFF')
            region=a[cy-1:cy+2,cx-1:cx+2,:].astype(int);expected=np.array(p['deviceRGB16'],int)
            error=int(np.max(abs(region-expected)));pixel=region[1,1,:]
            rows[i].update(tiffRGB16=pixel.tolist(),tiffMaxChannelCodeError=error)
            observed.append(pixel/65535);mismatches.append(error)
    except FileNotFoundError as e:
        result['tiff']['reason']='TIFF unavailable: '+str(e.filename);return result
    for file,(_,_,_,digest) in images.items():
        if sha(file)!=digest:raise ValueError('TIFF changed during chain diagnostic')
    result['tiff'].update(status='available',checkedCount=len(patches),mismatchCount=sum(e!=0 for e in mismatches),maxChannelCodeError=max(mismatches),tolerance16Codes=0)
    actual_lab=lookup(exe,profile,np.asarray(observed),'f','a')
    errors=[]
    for i,p in enumerate(patches):
        lab=measured_byid[str(p['id'])]['measuredLab'];de=float(colour.delta_E(actual_lab[i],lab,method='CIE 2000'))
        rows[i].update(tiffPredictedLab=actual_lab[i].tolist(),measuredVsTiffPredictionDE00=de)
        if unique[i]:errors.append(de)
    result['print'].update(status='available',summary=summary(errors))
    return result
